language: swift
os_image: xcode12.5
script: 
    xcodebuild clean build test -project NeewerLite/NeewerLite.xcodeproj -scheme NeewerLite --arch arm64 --arch x86_64 -configuration Debug ONLY_ACTIVE_ARCH=NO
