language: swift
os_image: xcode13.1
script: 
    xcodebuild clean build test -project NeewerLite/NeewerLite.xcodeproj -scheme NeewerLite -destination 'platform=macosx' -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    
