name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: pushd NeewerLite; swift build -v; popd;
    - name: Run tests
      run: pushd NeewerLite; swift test -v; popd;
